let moduleName = angular.module('shrine.constants', [])
    .constant('SHRINE_VERSION_API', 'v1')
    .constant('DEBUG_VIEWPORT_MODE', false)
    .constant('SHRINE_W_SIZES', [{
    		maxWidth: -1,
            minWidth: 1600,
    		viewport: "vp-xxlg",
            display: "desktop",
            orientation: false
    	}, {
    		maxWidth: 1599,
            minWidth: 1440,
    		viewport: "vp-xlg",
            display: "desktop",
            orientation: false
    	}, {
            maxWidth: 1439,
            minWidth: 1280,
            viewport: "vp-lg",
            display: "desktop",
            orientation: false
        }, {
            maxWidth: 1023,
            minWidth: 960,
            viewport: "vp-med",
            display: "desktop",
            orientation: false
        }, {
            maxWidth: 959,
            minWidth: 840,
            viewport: "vp-sm",
            display: "desktop",
            orientation: false
        }, {
            maxWidth: 719,
            minWidth: 601, //Interferes with Mobile landscape. Added (+1) as a hack
            viewport: "vp-xsm",
            display: "desktop",
            orientation: false
        }, {
            maxWidth: 599,
            minWidth: 480,
            viewport: "vp-xs",
            display: "desktop",
            orientation: false
        }, {
            maxWidth: 1279,
            minWidth: 1024,
            viewport: "vp-tablet-land",
            display: "mobile",
            orientation: "landscape"
        }, {
            maxWidth: 839,
            minWidth: 720,
            viewport: "vp-tablet-port",
            display: "mobile",
            orientation: false
        }, {
            maxWidth: 600,
            minWidth: 0,
            viewport: "vp-mobile-land",
            display: "mobile",
            orientation: "landscape"
        }, {
            maxWidth: 360,
            minWidth: -1,
            viewport: "vp-mobile-port",
            display: "mobile",
            orientation: false 
        }])
    .name;

export default moduleName;
